package com.app.tts.pojo;
// Generated Sep 25, 2020 2:22:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserToken generated by hbm2java
 */
public class UserToken  implements java.io.Serializable {


     private String id;
     private String createBy;
     private String name;
     private String token;
     private String state;
     private Date createAt;
     private Date updateAt;

    public UserToken() {
    }

	
    public UserToken(String id) {
        this.id = id;
    }
    public UserToken(String id, String createBy, String name, String token, String state, Date createAt, Date updateAt) {
       this.id = id;
       this.createBy = createBy;
       this.name = name;
       this.token = token;
       this.state = state;
       this.createAt = createAt;
       this.updateAt = updateAt;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Date getCreateAt() {
        return this.createAt;
    }
    
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }
    
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }




}


